metrics:
  map_loss: BCE
  map_depth: Depth
  map_chamfer: Chamfer

splits:
  all: ""
  indoor: ^indoor
  outdoor: ^outdoor
  bike: ^bike

reports:
  separate:
    name: Separate Splits
    methods: ["small/base", "small/indoor", "small/outdoor", "small/bike"]
    descriptions: ["all*", "indoor", "outdoor", "bike"]

  inputs:
    name: Input Representation
    methods: [
      "small/base", "small/pad", "small/amplitude", "small/shuffle",
      "small/rawdoppler", "small/cfar", "small/aoa"]
    descriptions: [
      "Base", "Padded", "Amplitude", "Shuffled",
      "Raw", "CFAR", "AOA"]

  patch:
    name: Encoder Patch Axes
    methods: [
      "small/base", "small/patch.dae", "small/patch.rae", "small/patch.rdae"]
    descriptions: ["RD*", "DAE", "RAE", "RDAE"]

  patchsize:
    name: Encoder Patch Size
    methods: [
      "small/base", "small/patch.rd2x", "small/patch.rd4x"]
    descriptions: ["128*", "256", "512"]

  balance:
    name: Balancing Coefficient
    methods: [
      "small/weight8", "small/base", "small/weight32", "small/weight64"]
    descriptions: ["8.0", "16.0*", "32.0", "64.0"]

  aug:
    name: Augmentations
    methods: ["small/base", "small/aug.lite", "small/aug.none"]
    descriptions: ["Full", "Partial", "None"]

  tiny:
    name: Data Scaling (Tiny)
    methods: ["tiny/p10", "tiny/p20", "tiny/p50", "tiny/base"]
    descriptions: ["10%", "20%", "50%", "100%"]

  small:
    name: Data Scaling (Small)
    methods: ["small/p10", "small/p20", "small/p50", "small/base"]
    descriptions: ["10%", "20%", "50%", "100%"]

  medium:
    name: Data Scaling (Medium)
    methods: ["medium/p10", "medium/p20", "medium/p50", "medium/base"]
    descriptions: ["10%", "20%", "50%", "100%"]

  large:
    name: Data Scaling (Medium)
    methods: ["large/p10", "large/p20", "large/p50", "large/base"]
    descriptions: ["10%", "20%", "50%", "100%"] 

  p10:
    name: Model Scaling (10%)
    methods: ["tiny/p10", "small/p10", "medium/p10", "large/p10"]
    descriptions: ["Tiny", "Small", "Medium", "Large"]

  p20:
    name: Model Scaling (20%)
    methods: ["tiny/p20", "small/p20", "medium/p20", "large/p20"]
    descriptions: ["Tiny", "Small", "Medium", "Large"]

  p50:
    name: Model Scaling (50%)
    methods: ["tiny/p50", "small/p50", "medium/p50", "large/p50"]
    descriptions: ["Tiny", "Small", "Medium", "Large"]

  p100:
    name: Model Scaling (100%)
    methods: ["tiny/base", "small/base", "medium/base", "large/base"]
    descriptions: ["Tiny", "Small", "Medium", "Large"]

comparisons:
  balance:
    baseline: small/base
    methods:
      small/weight8: {"weight": 8}
      small/base: {"weight": 16}
      small/weight32: {"weight": 32}
      small/weight64: {"weight": 64}
  separate:
    baseline: small/base
    methods:
      small/indoor: {"tsplit": "indoor"}
      small/outdoor: {"tsplit": "outdoor"}
      small/bike: {"tsplit": "bike"}
      small/base: {"tsplit": "all"}
  patch:
    baseline: small/base
    methods:
      small/patch.rdae: {"patch": "rdae"}
      small/patch.rae: {"patch": "rae"}
      small/patch.dae: {"patch": "dae"}
      small/base: {"patch": "rd"}
  augmentations:
    baseline: small/base
    methods:
      small/aug.none: {"aug": "full"}
      small/aug.lite: {"aug": "partial"}
      small/base: {"aug": "all"}
  input:
    baseline: small/base
    methods:
      small/pad: {"repr": "pad"}
      small/shuffle: {"repr": "shuffle"}
      small/rawdoppler: {"repr": "rawdoppler"}
      small/amplitude: {"repr": "amplitude"}
      small/cfar: {"repr": "cfar"}
      small/aoa: {"repr": "aoa"}
      small/base: {"repr": "complex"}
  patchsize:
    baseline: small/base
    methods:
      small/patch.rd2x: {"patch": 256}
      small/patch.rd4x: {"patch": 512}
      small/base: {"patch": 128}
  scale:
    baseline: small/p10
    methods:
      pico/p10: {"size": "p", "data": 10}
      pico/p20: {"size": "p", "data": 20}
      pico/p50: {"size": "p", "data": 50}
      pico/base: {"size": "p", "data": 100}
      tiny/p10: {"size": "t", "data": 10}
      tiny/p20: {"size": "t", "data": 20}
      tiny/p50: {"size": "t", "data": 50}
      tiny/base: {"size": "t", "data": 100}
      small/p10: {"size": "s", "data": 10}
      small/p20: {"size": "s", "data": 20}
      small/p50: {"size": "s", "data": 50}
      small/base: {"size": "s", "data": 100}
      medium/p10: {"size": "m", "data": 10}
      medium/p20: {"size": "m", "data": 20}
      medium/p50: {"size": "m", "data": 50}
      medium/base: {"size": "m", "data": 100}
      large/p10: {"size": "l", "data": 10}
      large/p20: {"size": "l", "data": 20}
      large/p50: {"size": "l", "data": 50}
      large/base: {"size": "l", "data": 100}
