metrics:
  map_loss: BCE
  map_depth: Depth
  map_chamfer: Chamfer

splits:
  all: ""
  indoor: ^indoor
  outdoor: ^outdoor
  bike: ^bike

methods:
  separate:
    name: Separate Splits
    methods: ["small/base", "small/indoor", "small/outdoor", "small/bike"]
    descriptions: ["all*", "indoor", "outdoor", "bike"]

  inputs:
    name: Input Representation
    methods: [
      "small/base", "small/pad", "small/amplitude", "small/shuffle",
      "small/rawdoppler", "small/cfar", "small/aoa"]
    descriptions: [
      "Base", "Padded", "Amplitude", "Shuffled",
      "Raw", "CFAR", "AOA"]

  patch:
    name: Encoder Patch Axes
    methods: [
      "small/base", "small/patch.dae", "small/patch.rae", "small/patch.rdae"]
    descriptions: ["RD*", "DAE", "RAE", "RDAE"]

  balance:
    name: Balancing Coefficient
    methods: [
      "small/weight8", "small/base", "small/weight32", "small/weight64"]
    descriptions: ["8.0", "16.0*", "32.0", "64.0"]

  aug:
    name: Augmentations
    methods: ["small/base", "small/aug.lite", "small/aug.none"]
    descriptions: ["Full", "Partial", "None"]

  tiny:
    name: Data Scaling (Tiny)
    methods: ["tiny/p10", "tiny/p20", "tiny/p50", "tiny/base"]
    descriptions: ["10%", "20%", "50%", "100%"]

  small:
    name: Data Scaling (Small)
    methods: ["small/p10", "small/p20", "small/p50", "small/base"]
    descriptions: ["10%", "20%", "50%", "100%"]

  medium:
    name: Data Scaling (Medium)
    methods: ["medium/p10", "medium/p20", "medium/p50", "medium/base"]
    descriptions: ["10%", "20%", "50%", "100%"]

  p10:
    name: Model Scaling (10%)
    methods: ["tiny/p10", "small/p10", "medium/p10"]
    descriptions: ["Tiny", "Small", "Medium"]

  p20:
    name: Model Scaling (20%)
    methods: ["tiny/p20", "small/p20", "medium/p20"]
    descriptions: ["Tiny", "Small", "Medium"]

  p50:
    name: Model Scaling (50%)
    methods: ["tiny/p50", "small/p50", "medium/p50"]
    descriptions: ["Tiny", "Small", "Medium"]

  p100:
    name: Model Scaling (100%)
    methods: ["tiny/base", "small/base", "medium/base", "large/base"]
    descriptions: ["Tiny", "Small", "Medium", "Large"]
